### ISSUE TITLE
Supporting imports

### ISSUE THREAD

**Issue by alexturpin** [openscd/xmlvalidate.js#4]
Hey! Thanks for the great library, I'm also trying to do XSD validation in the browser and found your comment here https://github.com/noppa/xmllint-wasm/issues/1#issuecomment-733824536

Unfortunately, my schema is spread across several different files and namespaces, and heavily leverages `<xsd:import>`s. Obviously that doesn't work (`Element '{http://www.w3.org/2001/XMLSchema}import': Failed to locate a schema at location 'my_schema_fragment.xsd'. Skipping the import.`), but I was wondering if anyone has tried this before, or knows how to approach the problem? Would there be a way to tweak the C code to support passing in multiple files?

Cheers!

**Comment by ca-d** [comment]
We solved this same problem by folding all the schema files into a single file. The C API in this thing currently has no support for several schema files with their filenames. This could be possible to adapt, though, if you still need this feature.
